### ISSUE TITLE
Sidekiq launcher shouldn't be required except when inside a Sidekiq process

### ISSUE THREAD

**Issue by arent-groebner** [ondrejbartas/sidekiq-cron#278]
I submitted a bug to the Sidekiq project and it turned out that it seems to be a sikdekiq-cron issue.

Please have a look here:

https://github.com/mperham/sidekiq/issues/4505

**Comment by mperham** [comment]
In fact there appears to be a lot of code loaded at all times which should only be loaded within the Sidekiq process. Use this pattern:

```ruby
Sidekiq.configure_server do
   require "..."
end
```

**Comment by sarahgriffis** [comment]
@arent-groebner ondrejbartas any tips?  Is this project still actively maintained?

**Comment by ondrejbartas** [comment]
@sarahgriffis  @arent-groebner hi can you try to use this new branch:

`gem 'sidekiq-cron', github: 'ondrejbartas/sidekiq-cron', branch: :"fix-launcher-problem"`

if it works for you? If it will work I will create new release

**Comment by digaoddc** [comment]
Hi @ondrejbartas I tested your new branch and it solved this issue

**Comment by sarahgriffis** [comment]
@ondrejbartas yes, this works!

**Comment by arent-groebner** [comment]
@ondrejbartas: Works for me to

**Comment by ondrejbartas** [comment]
thanks for verification I just released `sidekiq-cron (1.2.0)` so you can use it. I haven't deleted fix branch so it will not mess up your deployments.

**Comment by ondrejbartas** [comment]
Sorry for not fixing this earlier :/

**Comment by sarahgriffis** [comment]
No worries at all. We appreciate the quick resolution!

**Comment by arent-groebner** [comment]
Thanks for the fix!

**Comment by kimasenbeck** [comment]
@ondrejbartas I am still hitting this on v 1.2.0
I'm seeing `Redis::CannotConnectError: Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)` during `RUN bundle exec rake assets:precompile` after adding the sidekiq-cron dep. 
I attempted installing the gem from the branch you mentioned above as well. 
Can you suggest any workarounds in the meantime? Or other things I might be able to do to troubleshoot? 
I'm surprised to be hitting this since it sounds like it was indeed resolved in this version, so I'm not sure what's going on in my case.

**Comment by kimasenbeck** [comment]
> @ondrejbartas I am still hitting this on v 1.2.0 I'm seeing `Redis::CannotConnectError: Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)` during `RUN bundle exec rake assets:precompile` after adding the sidekiq-cron dep. I attempted installing the gem from the branch you mentioned above as well. Can you suggest any workarounds in the meantime? Or other things I might be able to do to troubleshoot? I'm surprised to be hitting this since it sounds like it was indeed resolved in this version, so I'm not sure what's going on in my case.

Update - I resolved this by adding `config.assets.initialize_on_precompile = false` to `config/application.rb`

**Comment by rahulnpadalkar** [comment]
@ondrejbartas This seems to be happening again with `sidekiq-cron v 1.12.0`. Is there any fix for this or do we need to downgrade?

**Comment by maciejb2k** [comment]
The error still occurs during the docker image build at the command `RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile`.

rails: `7.2.1`. ruby: `3.3.5`, sidekiq: `7.3.2`, sidekiq-cron: `1.12.0`

```
------
 > [build 6/6] RUN SECRET_KEY_BASE_DUMMY=1 ./bin/rails assets:precompile:
0.907 bin/rails aborted!
0.907 RedisClient::CannotConnectError: Connection refused - connect(2) for 127.0.0.1:6379 (redis://localhost:6379) (RedisClient::CannotConnectError)
0.907 /rails/config/initializers/sidekiq.rb:9:in `<main>'
0.907 /rails/config/environment.rb:5:in `<main>'
0.907
0.907 Caused by:
0.907 Errno::ECONNREFUSED: Connection refused - connect(2) for 127.0.0.1:6379 (Errno::ECONNREFUSED)
0.907 /rails/config/initializers/sidekiq.rb:9:in `<main>'
0.907 /rails/config/environment.rb:5:in `<main>'
0.907 Tasks: TOP => environment
0.907 (See full trace by running task with --trace)
0.910 2024-11-09T20:20:52.211Z pid=7 tid=42v INFO: Sidekiq 7.3.2 connecting to Redis with options {:size=>10, :pool_name=>"internal", :url=>"redis://localhost:6379/0"}
------
```
